### ISSUE TITLE
Possible memory leak issue with detect_intent method

### ISSUE THREAD

**Issue by tusharkoshti** [googleapis/python-dialogflow#105]
It seems whenever the detect_intent method is called memory usage of the python application increases by around 0.7 to 1 MB and the memory doesn't get released. Due to this memory usage of the python application increases with the number of calls to the detect_intent method.

Here is the code which seems to be having an issue.
```
response = session_client.detect_intent(
            session=session, query_input=query_input)
```

Note: text input is passed in the detect_intent method.

**Comment by tseaver** [comment]
@tusharkoshti I can't see anything in the generated [`SessionsClient.detect_intent`](https://github.com/googleapis/dialogflow-python-client-v2/blob/dfa2902aff563145d3e8f979c9f0b5581fbd0ac5/dialogflow_v2/gapic/sessions_client.py#L184-L271) implementation which would cause a leak.  Can you show how you are setting up `query_input`?

**Comment by tusharkoshti** [comment]
@tseaver - Here is the code snippet that we are using to set query_input

```
    text_input = dialogflow.types.TextInput(
            text='hi', language_code="en")

    query_input = dialogflow.types.QueryInput(text=text_input)

    response = session_client.detect_intent(
        session=session, query_input=query_input)
```

Note: We are running this python code on Windows OS.

Let me know if you need further more details on this.

**Comment by tseaver** [comment]
@tusharkoshti Are you creating a new `session_client` for each request?  We normally expect the client to be reused, held either as an attribute of a long-lived object or as a module global.

**Comment by tseaver** [comment]
> Is this documented anywhere or available in the sample snippets so that we would get to know how the client object should be used.

@tusharkoshti I don't think that we have that expectation documented clearly enough.  The issue with snippets is that they are very tightly focused, sort of like peering into a room through a keyhole:  you can see one part clearly (the feature being illustrated), but the big picture (what your whole application should look like) is obscured.

I am leaving the issue open to remind us that we need to document the bigger picture.

**Comment by lkameris** [comment]
i was experiencing the same issue as described above with the memory leak issue when refactored and changed the code  to fix this we have noticed that when running the more than 150 simultaneous calls we are having what seems to be retries of the same text.
here is a gist of the before and after. https://gist.github.com/lkameris/bfaafd43c399152039bea4162c2095f8 
no errors in the code just replays inside dialogflow console when the user is not saying that.
any help trying to resolve this would be highly appreciated.

**Comment by b-loved-dreamer** [comment]
This issue has been resolved. Closing now.
