### ISSUE TITLE
dialogflow interaction log

### ISSUE THREAD

**Issue by hueiyuanSu** [googleapis/python-dialogflow#108]
Excuse me.
I want to ask how to get interaction conversation log via python api.
I guess something function still not be opened.

In addition, I hope somebody can reply answer to me.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
