### ISSUE TITLE
Using .proto classes for log analysis.

### ISSUE THREAD

**Issue by Luttik** [googleapis/python-dialogflow#133]
Dialogflows logs to stackdriver could be a great source of insights, if we could analyse them properly. +/- half of the output is in protobuf's text format. However this library only contains a subset of the proto definitions used in these logs. It would ofcourse be awesome if you would add functionality for parsing the log. But it would also suffice if we simply have access to the proto definitions, such that we can compile the classes ourselves.

**Comment by busunkim96** [comment]
Hi @Luttik 

Our proto definitions are public. They live in [googleapis/googleapis](https://github.com/googleapis/googleapis). If you're looking for stackdriver logs, [google-cloud-python/7918](https://github.com/googleapis/google-cloud-python/issues/7918) may be of interest.

**Comment by Luttik** [comment]
I found that the protobuf output logged to stackdriver (in text form) via dialogflow logging don't match to the protobuf definitions in the googleapis repo. By now I've build a custom parser that doesn't use protobuf, but parses the text directly. So for my usecase the issue is solved. But for others it might still be super relevant to be able to parse the dialogflow history logs.

**Comment by busunkim96** [comment]
@Luttik Do the logs use the [Audit Logs](https://cloud.google.com/logging/docs/reference/audit/auditlog/rest/Shared.Types/AuditLog) format?

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
