### ISSUE TITLE
Rename package to `google-cloud-dialogflow` to follow naming convention

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-dialogflow#168]
All other Python cloud packages are named `google-cloud-*`. For consistency, dialogflow should also be renamed to `google-cloud-dialogflow`.

Steps:
1. Publish a last release of `dialogflow` with a note in the README directing users to the new package.
2. Change the package name to `google-cloud-dialogflow`.
3. Publish the first release of `google-cloud-dialogflow`.

CC @nnegrey

**Comment by nnegrey** [comment]
Would this move all client library code to `google-cloud-python` repo?
All samples would also need to be updated with this and docs.

**Comment by busunkim96** [comment]
We're actually splitting the big repository out into smaller ones, so I think this repository can remain unchanged.

**Comment by busunkim96** [comment]
This is done, although there's some lingering questions about how to signal to users that they should move to the new package. That's tracked in #243
