### ISSUE TITLE
webhook_state has incorrect value

### ISSUE THREAD

**Issue by trevor-pope** [googleapis/python-dialogflow#198]
1. Currently on Windows (AMD64) 
2. Python version 3.8.1
3. dialogflow version 1.0.0 (not using V2_Beta)

On my Dialogflow Console, my agent has Webhook enabled, and for all of my intents "Enable webhook call for this intent" is selected. However,
`response.query_result.intent.webhook_state == dialogflow.enums.Intent.WebhookState.WEBHOOK_STATE_UNSPECIFIED`always returns True, i.e. webhook_state is 0 (webhook unspecified). I am doing streaming detect intent, and the webhook works fine. 

Is this the right way to determine if a webhook call was used for an Intent, or am I misunderstanding what webhook_state means?

**Comment by munkhuushmgl** [comment]
@trevor-pope Sorry about late response,

Could you make sure that you have webhook turned on in fulfillment?

**Comment by trevor-pope** [comment]
No problem.

Yes, [webhook is turned on](https://i.imgur.com/JGUzoq9.png), and I have [webhook call enabled](https://i.imgur.com/r73tBaw.png) for my intents.

**Comment by lucaswadedavis** [comment]
Would you mind sharing some code, so we can get a clearer view of what's going on?

**Comment by trevor-pope** [comment]
Here is a minimum viable example, using Flask and Ngrok for the webhook.

Get [ngrok](https://ngrok.com/) and run it in your terminal:
`ngrok http 5000`

then run webhook.py
```
import time
import json
from flask import Flask, make_response, jsonify

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def webhook():
    return make_response(jsonify({'fulfillment_text': "The time is " + str(time.time())}))

if __name__ == '__main__':
    app.run()
```

and to test the bug run detect_intent.py:
```
import flask
import dialogflow_v2 as dialogflow
import os

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'PATH/TO/CREDENTIALS'
session_client = dialogflow.SessionsClient()
session = session_client.session_path(project='MY_PROJECT_NAME', session='my_session')

text = 'What time is it?'
text_input = dialogflow.types.TextInput(text=text, language_code='en')
query_input = dialogflow.types.QueryInput(text=text_input)
response = session_client.detect_intent(session=session, query_input=query_input)
intent = response.query_result.intent

print('Webhook Status: ', response.webhook_status)
print('Fulfillment Text: ', response.query_result.fulfillment_text)
print('Webhook enabled: ', intent.webhook_state in {intent.WEBHOOK_STATE_ENABLED, intent.WEBHOOK_STATE_ENABLED_FOR_SLOT_FILLING})
```

The agent I used to test:
[TestAgent.zip](https://github.com/googleapis/dialogflow-python-client-v2/files/4922373/TestAgent.zip)

It has fulfillment enabled, and the time intent has webhook enabled. 

Dialogflow will obviously reach the webhook since response.webhook_status will be "Webhook execution successful", and it has retrieved the fulfillment text, but webhook_state will always be 0 (i.e. [WEBHOOK_STATE_UNSPECIFIED](https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Intent.WebhookState)).

I tested this on dialogflow==1.0.0.

**Comment by trevor-pope** [comment]
Any word on this?

**Comment by lucaswadedavis** [comment]
Okay, I see what you're doing.

First, but less important, your response isn't structured in a way that Dialogflow can understand. Check [this](https://cloud.google.com/dialogflow/docs/fulfillment-webhook#text_response) out for the right structure.

Second, and more important, rather than writing your own fulfillment logic, consider using the Dialogflow library to handle fulfillment logic. I recommend [this](https://cloud.google.com/dialogflow/docs/quick/fulfillment) quickstart guide.

**Comment by trevor-pope** [comment]
In my actual application I use the fulfillment_messages[] field, I was just using the [deprecated](https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#webhookresponse) text field for simplicity.

I have my own webhook that runs on AWS that works fine as far as I am aware, this example was just to demonstrate the bug. Is there a reason why `intent.webhook_state` always returns 0 no matter if the intent had webhook fulfillment enabled or not?

**Comment by b-loved-dreamer** [comment]
Hi @trevor-pope — I am sorry is been very long since our last reply. I am not sure this issue is sill relevant so I for now I am closing it. If you still would like, you can reopen as needed.
