### ISSUE TITLE
Usage documentation link does not go to usage documentation

### ISSUE THREAD

**Issue by staticdev** [googleapis/python-dialogflow#203]
#### Environment details

1. OS type and version: N/A
2. Python version and virtual environment information: N/A
3. dialogflow version:  `pip show dialogflow` or `pip freeze`: 1.0.0

#### Steps to reproduce

  1. Enter the link https://googleapis.dev/python/dialogflow/latest/index.html
  2. Click on Usage documentation.

#### Code example

N/A

#### Stack trace

N/A

Thanks!

**Comment by munkhuushmgl** [comment]
@staticdev I just added to my hotlist, and will get back to you soon.

**Comment by busunkim96** [comment]
Hm, I don't see this in the current README, so it must have been fixed (but not yet released).

https://github.com/googleapis/dialogflow-python-client-v2#dialogflow-python-client

**Comment by munkhuushmgl** [comment]
> Hm, I don't see this in the current README, so it must have been fixed (but not yet released).
> 
> https://github.com/googleapis/dialogflow-python-client-v2#dialogflow-python-client

Okay thanks for quick response.
