### ISSUE TITLE
Is it possible to enable/disable a knowledge base using the python api? Or enable one by default when creating it?

### ISSUE THREAD

**Issue by lbcastro** [googleapis/python-dialogflow#209]
Inside the Knowledge tab, we can enable/disable specific Knowledge Bases by selecting them and pressing Enable or Disable. Also, when a new Knowledge Base is created using the Python API, it's disabled by default.

I've looked around this library and couldn't find any way to toggle this setting or to enable a newly created knowledge base by default; I've also failed to find any parameters in the KnowledgeBase object that refers to enabling it.

Is it currently possible to do this using the Python API? Thanks.

**Comment by b-loved-dreamer** [comment]
Hi @lbcastro — it looks like this can only be done from the console. 

Resource: https://developers.google.com/resources/api-libraries/documentation/dialogflow/v2beta1/java/latest/com/google/api/services/dialogflow/v2beta1/model/GoogleCloudDialogflowV2beta1KnowledgeBase.html

This issue has been inactive for a while and maybe irrelevant at this point. I am closing it but please feel free reopen if you still need help.
