### ISSUE TITLE
Please re-introduce `end_interaction` in `dialogflow.types.Intent`

### ISSUE THREAD

**Issue by alecokas** [googleapis/python-dialogflow#210]
It looks like the `end_interaction` field for an Intent type is no longer available in `v2`. I am not sure if the functionality to create an intent which when triggered flags the end of an interaction has simply moved since `v2_beta1`, but I am unable to find it.

 **Is your feature request related to a problem? Please describe.**
I'd like to be able to indicate that the intent should end the current interaction.
 **Describe the solution you'd like**
I'd like the `end_interaction` field (as present in v2_beta1) to be re-introduced please
 **Describe alternatives you've considered**
None available as far as I can tell.
 **Additional context**
I'm not sure if this is a regression bug or a strategic decision which has been made since the v2 documentation still refers to  the field [here](https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#queryresult) even though it is not present [here](https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#intent).

**Comment by alfonsozunigaj** [comment]
@munkhuushmgl @alecokas have there been any advances on this? I too noticed that you can't create an end-of-conversation intent using the python library.

**Comment by alecokas** [comment]
@alfonsozunigaj No updates from what I can tell - I managed to work around it in my project.

**Comment by b-loved-dreamer** [comment]
Hi @alecokas. The ```end_interaction``` seems to still be present in the docs you referenced above. You can also manually set an intent to ```end of conversation```.

From the DialogFlow Console:

<img width="407" alt="Screen Shot 2021-05-26 at 11 07 22 AM" src="https://user-images.githubusercontent.com/69214580/119709892-939a8c00-be12-11eb-8eec-eae37a067b2f.png">

I am now closing this issue. Please feel free to reopen.
