### ISSUE TITLE
model selection and data logging

### ISSUE THREAD

**Issue by tekkkon** [googleapis/python-dialogflow#224]
Hi,
By reading the enhanced speech model and data logging description from the [product page](https://cloud.google.com/dialogflow/es/docs/data-logging). Looks like enhanced speech model and data logging are bundled together, is there a way to decouple them so developer can use the enhanced model without opt in for data logging?

![image](https://user-images.githubusercontent.com/6827543/91909124-7f4da800-ec61-11ea-83f5-cb38a7e6a706.png)

Thanks

**Comment by b-loved-dreamer** [comment]
Hi @tekkkon — No, the ```enhanced model```  and ```data logging``` features are coupled and hence cannot be used separately. 

We hope this answers your question. I am now closing this issue.
