### ISSUE TITLE
Slow response from API

### ISSUE THREAD

**Issue by mclgoerg** [googleapis/python-dialogflow#231]
Hi,

I am facing a issue which I thought you may help me.
I am using Dialogflow to detect intents based on a text query. After setting up, I call:

**response = session_client.detect_intent(
session=session, query_input=query_input)**

Full Code:
```
def detect_intent_texts(project_id, session_id, texts, language_code):
    """Returns the result of detect intent with texts as inputs.
    Using the same `session_id` between requests allows continuation
    of the conversation."""
    import dialogflow_v2 as dialogflow
    session_client = dialogflow.SessionsClient()

    session = session_client.session_path(project_id, session_id)
    print('Session path: {}\n'.format(session))

    for text in texts:
        text_input = dialogflow.types.TextInput(
            text=text, language_code=language_code)

        query_input = dialogflow.types.QueryInput(text=text_input)
        try:
            response = session_client.detect_intent(session=session, query_input=query_input)
        except InvalidArgument:
            raise

        print('=' * 20)
        print('Query text: {}'.format(response.query_result.query_text))
        print('Detected intent: {} (confidence: {})\n'.format(
            response.query_result.intent.display_name,
            response.query_result.intent_detection_confidence))
        print('Fulfillment text: {}\n'.format(
            response.query_result.fulfillment_text))

if __name__ == '__main__':
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'private_key.json'
    DIALOGFLOW_PROJECT_ID = 'dialogflowslack'
    SESSION_ID = 'me'
    DIALOGFLOW_LANGUAGE_CODE = 'de'
    text_to_be_analyzed = ["test", "hallo"]

    detect_intent_texts(
        DIALOGFLOW_PROJECT_ID, SESSION_ID, text_to_be_analyzed, DIALOGFLOW_LANGUAGE_CODE)
```

This takes very long (> 1min) for the first text element ("test") but is instant for the second element ("hallo") or any other element following. After some time the session client seems to timeout again and I have to wait again for > 1 minute.  
I want to use send user input via the session client to the dialog flow api to get the intents back. But its too much if a user has to wait 1 minute for the first response.

There is no debug information nor errors.

Do you know what the issue may be?

The code used is directly from:
http://dialogflow-python-client-v2.readthedocs.io/en/latest/?#using-dialogflow

**Comment by mclgoerg** [comment]
For anyone else with the same issue - Sometimes the smallest things have the biggest impact.
I connected my local client to a personal hotspot and got instant replies.
Turned wifi off & on -> instant replies aswell.
I can't explain the solution but it might help for other users.

**Comment by munkhuushmgl** [comment]
@mclgoerg Is this related to this problem?
https://stackoverflow.com/questions/52561789/slow-time-response-on-dialogflow-fullfilment-http-requests

**Comment by b-loved-dreamer** [comment]
This issue seems to no longer be relevant, so I am closing it. Feel free reopen if needed.
