### ISSUE TITLE
How to select a region with the python client?

### ISSUE THREAD

**Issue by lsyin** [googleapis/python-dialogflow#233]
Hi, guys, there is something wrong when I using the python client, because of dialogflow have different regions, every region has each agent, the client's default region is US, but when I want to select other region, I can't find any parameter and method helping me do it. Could you help me to solve it, thanks very much.

**Comment by munkhuushmgl** [comment]
@lsyin Which version of dialogflow are you using?

Client's region meaning the endpoint? 
https://github.com/googleapis/dialogflow-python-client-v2/blob/c1c925d94726f49e549870e087ad79ee491056e2/dialogflow_v2/gapic/intents_client.py#L63

If you are trying to change the endpoint, you can do it the following:
```
    client_options = {"api_endpoint": api_endpoint}
    client = dialogflow.IntentsClient(client_options=client_options)
```

**Comment by lsyin** [comment]
> dialogflow-python-client-v2/dialogflow_v2/gapic/intents_client.py

thanks very much,I have already done that, but the new issue come, here is the pic:
<img width="1211" alt="截屏2020-11-23 下午10 32 44" src="https://user-images.githubusercontent.com/7400702/100070619-1b5c0980-2e75-11eb-8f51-dbbb1a8bb33f.png">
<img width="964" alt="截屏2020-11-23 下午10 32 08" src="https://user-images.githubusercontent.com/7400702/100070570-0f704780-2e75-11eb-8dd3-5f425e67a55c.png">
I don't know how it works.Are there exist a client and a server in same region that I must config? It seems I only configure the server, but how can I config the client?

**Comment by munkhuushmgl** [comment]
Looks like your resources located in us. I think your endpoint should be US.

Could you share some code snippet you used to trigger this error?

**Comment by lsyin** [comment]
Sure, the main code is below:
`
project_id = "XXX-dialogflowdev"
session_id = "session-id-0004-3243242"
language_code = 'en-US'
def detect_intent_event(event_name):
    options=ClientOptions(api_endpoint="asia-northeast1-dialogflow.googleapis.com:443",scopes="https://www.googleapis.com/auth/cloud-platform")
    session_client = dialogflow.SessionsClient(client_options=options)
    session = session_client.session_path(project_id, session_id)
    parameters = struct_pb2.Struct()
    parameters["uid"] = '111111'
        
    event_input = dialogflow.types.EventInput(name=event_name, language_code=language_code, parameters = parameters)
    query_input = dialogflow.types.QueryInput(event=event_input)
        
    response = session_client.detect_intent(session=session, query_input=query_input)
    return response
response = detect_intent_event('event_1')

what's resource you mean? A project has a region,  a region has a agent. I create a us agent and a tokyo agent.I want to use the tokyo agent but I don't know how can I  attach it, the default is us. When I changed the endpoint ,the new issue came above.
`

**Comment by munkhuushmgl** [comment]
@lsyin I do not think you set different region on client_options. Looks like your all resources are located in US even though agent is based on japan or different region.

**Comment by munkhuushmgl** [comment]
@lsyin There is new version that came out which will enable multil region feature

https://cloud.google.com/dialogflow/cx/docs/how/region

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
