### ISSUE TITLE
Unable to get details of Context from response.query_result

### ISSUE THREAD

**Issue by gitefeb** [googleapis/python-dialogflow#234]
I need to read the information inside response.query_result.output_contexts but it seems that client library either missing some elements or missing the functionality to decode that part of the message. I would expect it to return either a Dict, JSON or Object just like on other method parameters but it returns an unformatted string.

#### Environment details

1. MacOS Catalina v10.15.7 and Docker Container
2. Python version and virtual environment information: Python 3.8.5
3. dialogflow version:  dialogflow version:
Name: dialogflow
Version: 0.7.2
Summary: UNKNOWN
Home-page: https://github.com/dialogflow/dialogflow-python-client-v2
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/mac/Desktop/Profilo Product Mix Optimization/chatbot_platform/venv/lib/python3.8/site-packages
Requires: google-api-core
Required-by:

#### Steps to reproduce

1. Initialize your dialogflow agent, GCP Keys and local dev environment(ref)
2. Create a Virtual Environment and install dialogflow python client library
3. Change the response of Default Welcome Intent to "Hello, please enter first parameter(param1) to begin."
4. Create the intents below on dialogflow UI(ES)
> Default Welcome Intent - custom(Follow up intent) / Training Phrase: 001232(define as param1:@sys.number) / Response: Please enter param2

> Default Welcome Intent - custom - custom (Follow up intent) / Training Phrase: 001232(define as param2:@sys.number) / Response: Please enter param3

> Default Welcome Intent - custom - custom - custom(Follow up intent) / Training Phrase: 001232(define as param3:@sys.number) / Response: Ok, I got all your params

Please note that the intents above are in hierarchical order as Follow Up of each other.
5.Run the code below and send the params to dialogflow using session_client.detect_intent method.
6.Analyze the response.query_result.output_contexts and you will see this value actually has all 3 params inside it but there is no way of extracting them in the library since they are in a weird text format. I also tried using protobuf methods to decode it but that approach was not successful as well.

#### Code example

```python

import json
import dialogflow
from google.protobuf import struct_pb2
import os
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'YOUR JSON KEY DIR'
project_id = 'YOUR PROJECT ID'

def set_session(session_key):
    """Sets Google Dialogflow session with unique user session key.

    session_key(str): Unique session key.

    Returns:
    session_client(dialogflow.SessionsClient): SessionsClient instance.
    google_session(dialogflow.SessionsClient.session):Dialogflow Session instance.

    """

    session['key'] = session_key
    session_client = dialogflow.SessionsClient()
    google_session = session_client.session_path(project_id, session_key)

    return session_client, google_session

text_input = dialogflow.types.TextInput(text="Hello",  language_code="en")
query_input = dialogflow.types.QueryInput(text=text_input)
response = session_client.detect_intent(session=google_session, query_input=query_input)

text_input = dialogflow.types.TextInput(text="00001",  language_code="en")
query_input = dialogflow.types.QueryInput(text=text_input)
response = session_client.detect_intent(session=google_session, query_input=query_input)

text_input = dialogflow.types.TextInput(text="00002",  language_code="en")
query_input = dialogflow.types.QueryInput(text=text_input)
response = session_client.detect_intent(session=google_session, query_input=query_input)

text_input = dialogflow.types.TextInput(text="00003",  language_code="en")
query_input = dialogflow.types.QueryInput(text=text_input)
response = session_client.detect_intent(session=google_session, query_input=query_input)

print(response.query_result.output_contexts)
```

#### Stack trace
```
N/A
```

I would like to extract and use the parameters inside response.query_result.output_contexts but I couldnt find an official method in the library. I dont think it is appropriate to manually serialize it by string manipulations. Could you please let me know how can I extract past parameters?

Thanks!

**Comment by munkhuushmgl** [comment]
Have you tried printing out just query result?

```
print(response.query_result)
```

**Comment by munkhuushmgl** [comment]
@busunkim96 Could you help with this? seems like library related question

**Comment by busunkim96** [comment]
It looks like `output_contexts` is a repeated field, so you could try something like this:

```py

for context in response.query_result.output_contexts:
    print(context.parameters)
```

`context.parameters` is a protobuf [struct](https://developers.google.com/protocol-buffers/docs/reference/python-generated#struct) and it is somewhat like a dictionary.

**Comment by gitefeb** [comment]
Hi @busunkim96, thanks for the response. I am not sure if you have followed the steps that I have mentioned on the issue description but I dont think I have all the answers. So here is a further explanation. I dont think I can retrieve the data inside context.parameters because it does not look like a struct and looks more like list of a struct. I tried printing the struct value(output_contexts) and got the following:
`
for context in response["query_result"].output_contexts:
    if context.name == "projects/PROJECT_NAME/agent/sessions/SESSION_NAME/contexts/__mega_agent_context__":
        print(type(context.parameters))
        print(context.parameters)
`
![image](https://user-images.githubusercontent.com/36018950/101083231-9fbd3380-35bd-11eb-8eb6-f6655d9cb7d4.png)

When I try to iterate through fields inside it using a for loop it returns keys of those fields as strings therefore I can not retrieve the values. Here is the code and output:
`for context in response["query_result"].output_contexts:
                if context.name == "projects/PROJECT_NAME/agent/sessions/SESSION_NAME/__mega_agent_context__":
                    for field in context.parameters:
                        print(type(field))
                        print(field)`
![image](https://user-images.githubusercontent.com/36018950/101084098-88327a80-35be-11eb-84eb-69ea431455f7.png)

How would you get the parameters considering the situation above?

Thanks.

**Comment by gitefeb** [comment]
P.S.

> It looks like `output_contexts` is a repeated field, so you could try something like this:
> 
> ```python
> for context in response.query_result.output_contexts:
>     print(context.parameters)
> ```
> 
> `context.parameters` is a protobuf [struct](https://developers.google.com/protocol-buffers/docs/reference/python-generated#struct) and it is somewhat like a dictionary.

Btw `response.query_result.output_contexts` approach returns the following error, so I use `response.["query_result"].output_contexts` as stated on my previous reply above.
<img width="479" alt="image" src="https://user-images.githubusercontent.com/36018950/101089677-8c629600-35c6-11eb-8aca-c46cb055f68f.png">

**Comment by busunkim96** [comment]
@gitefeb Ah sorry about that.

Can you try iterating through `.items()` instead?
```py
for context in response["query_result"].output_contexts:
    if context.name == "projects/PROJECT_NAME/agent/sessions/SESSION_NAME/__mega_agent_context__":
        for key, value in context.parameters.items():
            print(f"{key}: {value}")
```

The way protobuf presents the struct when you `print()` is a bit weird (looks like a list), but it does somewhat behave like a dictionary.

```py
from google.protobuf import struct_pb2

s = struct_pb2.Struct()
s["a"] = 1 
s["b"] = 2

for k, v in s.items():
    print(f"{k}: {v}")
```

Output:
```
a: 1.0
b: 2.0
```

If you'd prefer to work with a proper python dict you can also convert it using [`json_format.MessageToDict`](https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html#google.protobuf.json_format.MessageToDict):

```py
from google.protobuf import json_format

json_format.MessageToDict(context.parameters)
```

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue.

**Comment by Archetype90** [comment]
> ```python
> from google.protobuf import json_format
> 
> json_format.MessageToDict(context.parameters)
> ```

Sorry to resurrect an old thread, but I am encountering an issue related to this. I had been using Dialogflow 1.1 for the longest time, where the above code was the solution to parsing parameters. The data type of query_result.parameters was a struct, and the above method worked beautifully.

But, after upgrading to V2.7.1 and following the migration guide (https://googleapis.dev/python/dialogflow/latest/UPGRADING.html) I am now getting the following error when attempting to use the above method:

```
  File "C:\Projects\test\dialogflow.py", line 102, in detect_intent_text
    parameters = json.loads(MessageToJson(query_result.parameters))
  File "C:\Projects\test\venv\lib\site-packages\google\protobuf\json_format.py", line 137, in MessageToJson
    return printer.ToJsonString(message, indent, sort_keys)
  File "C:\Projects\test\venv\lib\site-packages\google\protobuf\json_format.py", line 204, in ToJsonString
    js = self._MessageToJsonObject(message)
  File "C:\Projects\test\venv\lib\site-packages\google\protobuf\json_format.py", line 209, in _MessageToJsonObject
    message_descriptor = message.DESCRIPTOR
```

I have been able to get around this issue by iterating through the items() in the MapComposite and creating my own dictionary, but the above method (which I would prefer to use) does not seem to work.
