### ISSUE TITLE
How to set intent_view to FULL_INTENT_VIEW

### ISSUE THREAD

**Issue by sanjitpush** [googleapis/python-dialogflow#283]
Hi,
   I'm trying to write a script that gets all the training phrases of a given intent, however when get_intent is called the intent returned does not contain the training phrases. I saw that you need to set the intent_view to FULL_INTENT_VIEW in some issue threads and on the API docs, but it was not specified on how to set the intent view. If anyone can help out, would really appreciate it.

**Comment by b-loved-dreamer** [comment]
Hi @sanjitpush — thank you for filing this issue. I constructed a sample that achieves your stated goal:

> from google.cloud import dialogflow # Grab the client lib.
>
> intent_client = dialogflow.IntentsClient() # Construct an IntentClient object 
>
> intent_name = 'projects/<Project ID>/agent/intents/<Intent ID>' # Your specific working intent
>
> intent_view = dialogflow.IntentView.INTENT_VIEW_FULL # The IntentView, which allows all fields to be populated.
>
> get_intent_request = dialogflow.GetIntentRequest(name=intent_name, intent_view=intent_view) # Package the request
>
> intent = intent_client.get_intent(get_intent_request) # Submit the request and get the intent returned by the client
>
> print('Training  Phrases: {}'.format(intent.training_phrases)) # Print your training phrases

Your intent id has the format /[a-z][0-9]-/. This [sample](https://cloud.google.com/dialogflow/es/docs/how/manage-intents) can help you find it.

The resources I used to construct this sample:
https://googleapis.dev/nodejs/dialogflow/latest/google.cloud.dialogflow.v2beta1.GetIntentRequest.html
https://googleapis.dev/java/google-cloud-dialogflow/latest/com/google/cloud/dialogflow/v2/IntentView.html
https://cloud.google.com/dialogflow/es/docs/reference/rest/v2/IntentView
https://googleapis.dev/ruby/google-cloud-dialogflow/latest/Google/Cloud/Dialogflow/V2/IntentsClient.html#get_intent-instance_method
https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/api/Google.Cloud.Dialogflow.V2.IntentsClient.html
https://developers.google.com/resources/api-libraries/documentation/dialogflow/v2/csharp/latest/classGoogle_1_1Apis_1_1Dialogflow_1_1v2_1_1ProjectsResource_1_1AgentResource_1_1IntentsResource_1_1GetRequest.html

---------------------------------------------------
Please let me know if this helps.

**Comment by sanjitpush** [comment]
This did the trick! Thank you for the help.
