### ISSUE TITLE
Minimum working code

### ISSUE THREAD

**Issue by Pro100rus32** [googleapis/python-dialogflow#309]
**Can someone give a minimum working code(chat bot)?** 

_I couldn't even find how to import the library, because the installed library has a different name to import._

**Comment by munkhuushmgl** [comment]
For setup, refer to the following docs:
https://cloud.google.com/dialogflow/es/docs/quick/setup

for basic operation with dialogflow:

- interaction with API

> https://cloud.google.com/dialogflow/es/docs/quick/api

https://github.com/googleapis/python-dialogflow/blob/d2b9923a5ec3c06d694aeacef89b477ce92b4cbd/samples/snippets/detect_intent_texts.py#L17-L63
