### ISSUE TITLE
Illegal Instruction over Armv8 (Odroid C2)

### ISSUE THREAD

**Issue by Nestortnd** [googleapis/python-dialogflow#348]
Illegal instruction appears when trying to run the code (Python) offered by Google as an example.
On X86_64 architecture it works perfectly. In an implementation in Odroid C2 the error appears.
On both machines I installed with **pip install google-cloud-dialogflow.**
Running Python in interactive mode, it is seen that the error does not appear in the import (f**rom google.cloud import dialogflow**), but when obtaining the client session (**session_client = dialogflow.SessionsClient**)
I found browsing who said that there were Google binaries compiled for other architectures not compatible with Armv6. Not my case (Armv8). I did not advance further from there.
Thanks

**Comment by b-loved-dreamer** [comment]
Hi @Nestortnd. Are trying to run a ```google-cloud-dialogflow``` python sample from a ARM based system?

The [docs](https://cloud.google.com/dialogflow/es/docs/quick/setup#auth-env) do not mention support for other architectures so I would assume that's the issue here.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
