### ISSUE TITLE
AttributeError: module 'google.cloud.dialogflow_v2' has no attribute 'Entity'

### ISSUE THREAD

**Issue by xiaoliqing1001** [googleapis/python-dialogflow#573]
Hi Team,
I ran the sample and got an error, "AttributeError: module 'google.cloud.dialogflow_v2' has no attribute 'Entity'".
https://github.com/googleapis/python-dialogflow/blob/main/samples/generated_samples/dialogflow_generated_dialogflow_v2_entity_types_batch_delete_entity_types_sync.py

By the way, how to get the "Entity Type ID"?
parent (str) – Required. The name of the entity type to create entities in. Format: projects/[Project ID]/agent/entityTypes/[Entity Type ID].
This corresponds to the parent field on the request instance; if request is provided, this should not be set.
(https://googleapis.dev/python/dialogflow/latest/dialogflow_v2/entity_types.html)

Could you give me a complete sample?

Thanks.

**Comment by mattcarrolldev** [comment]
@xiaoliqing1001 if you have a general question on how to get started please use another forum link StackOverflow. If you are looking for some more in depth documentation and guides please see this page: https://cloud.google.com/dialogflow/cx/docs/tutorials
