### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'index'

### ISSUE THREAD

**Issue by ElissonRodrigues** [googleapis/python-dialogflow#598]
#### Environment details

  - OS type and version:
  - Python version: `3.11`
  - pip version: `22.3.1`
  - `google-cloud-dialogflow` version: `2.16.1`

#### Steps to reproduce

  to reproduce to install python3.11 and import the agent:
  ```python
  from google.cloud.dialogflow_v2beta1.types import agent
  ```

#### Traceback

from google.cloud.dialogflow_v2beta1.types import agent                                       File "/usr/local/lib/python3.11/dist-packages/google/cloud/dialogflow_v2beta1/types/__init__.py", line 103, in <module>                           from .document import (                       File "/usr/local/lib/python3.11/dist-packages/google/cloud/dialogflow_v2beta1/types/document.py", line 44, in <module>                            class Document(proto.Message):                File "/usr/local/lib/python3.11/dist-packages/google/cloud/dialogflow_v2beta1/types/document.py", line 135, in Document                           class KnowledgeType(proto.Enum):              File "/usr/local/lib/python3.11/dist-packages/proto/enums.py", line 61, in __new__                idx = attrs._member_names.index(pb_options)           ^^^^^^^^^^^^^^^^^^^^^^^^^             AttributeError: 'dict' object has no attribute 'index'

**Comment by parthea** [comment]
Fixed in https://github.com/googleapis/python-dialogflow/releases/tag/v2.18.0
